### ISSUE TITLE
Attribute values are not processed when they are indented

### ISSUE THREAD

**Issue by TristanCacqueray** [ansible/anonymizer#57]
* Anonymizer version: master
* Python version: 3.11
* Operating System: fedora

### Description

The following example is not anonymized:

```yaml
# test.yaml
- name: a task
  a_module:
    secret: >
      foobar 
```

### What I Did

```
$ python3 -m ansible_anonymizer.cli ./test.yaml 
- name: blah
  a_module:
    secret: "{{ secret }}"
      foobar
```

I expected the output to be consistent with the example from the README.
